# This workflow will install Python dependencies and run a basic test to ensure
# that the Cloud/Azure CLI is still working
name: Test Azure CLI

# TODO: enable these tests again once the repository is in the public domain 

# on:
#   push:
#     branches: ["main"]
#     paths:
#       - toolchain/src/turnkeyml/cli/scale/**
#   pull_request:
#     branches: ["main"]
#     paths:
#       - toolchain/src/turnkeyml/cli/scale/**

# In the meantime, allow manual execution
on:
  # Allows users to manually trigger the workflow using the GitHub UI
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_and_test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: tkml
          python-version: "3.8"
      - name: Install dependencies
        shell: bash -el {0}
        run: |
          sudo apt-get update
          sudo apt-get install -y azure-cli
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r toolchain/src/turnkeyml/cli/cloud/requirements.txt
      - name: Run tests
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          TURNKEY_AZURE_PUBLIC_KEY: ${{ secrets.AZURE_SSH_PUBLIC_KEY }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TURNKEY_AZURE_PASSWORD: ${{ secrets.TURNKEY_AZURE_PASSWORD }}
        shell: bash -el {0}
        run: |
          az login --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_PWD }}

          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.AZURE_SSH_PRIVATE_KEY }}"

          mkdir ~/.ssh
          touch ~/.ssh/known_hosts

          cd src/turnkeyml/cli/cloud

          python control.py create setup selftest info stop --name github-test-azure-single --hardware cpu-small

          python control.py create setup selftest info stop --cluster --name github-test-azure-cluster --size 2 --hardware cpu-small
          python control.py start run --cluster --name github-test-azure-cluster --size 2 --hardware cpu-small --input-files onnxmodelzoo/toolchain/models/selftest/*.py
  clean_up:
    needs: build_and_test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install az cli
        run: |
          sudo apt-get update
          sudo apt-get install -y azure-cli
      - name: Delete resource group
        run: |
          az login --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_PWD }}
          az group delete --name github-test-azure-single-rg --yes
          az group delete --name github-test-azure-cluster-rg --yes
